version: "3.7"

services:
  node-red:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "1880:1880"
      - "3456:3456"
    networks:
      - node-red-net  
    container_name: node-red
    restart: always

networks:
  node-red-net:

